FROM ubuntu:groovy

LABEL maintainer="Ian Rambo" email="ian.rambo@utexas.edu" desc="CRISPRCasFinder-4.2.20"

USER root

ARG USER_ID
ARG GROUP_ID
ARG DEBIAN_FRONTEND=noninteractive

RUN mkdir -p /build

WORKDIR /build

RUN apt-get -y update \
    && apt-get -y upgrade \
    && apt-get -y install software-properties-common \
    && apt-add-repository universe \
    && apt-get -y update \
    && apt-get -y install apt-utils \
        wget \
        curl \
        git \
        default-jre \
        python2 \
        parallel \
        cpanminus \
        gcc \
        make \
        hmmer \
        emboss \
        emboss-lib \
        ncbi-blast+ \
        bioperl \
        bioperl-run \
        libdatetime-perl \
        libxml-simple-perl \
        libdigest-md5-perl \
        muscle \
        prodigal \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y

RUN curl https://bootstrap.pypa.io/get-pip.py --output get-pip.py \
    && python2 get-pip.py \
    && pip2 install coverage python-coveralls

RUN cpanm --force Unix::Sysexits \
    Try::Tiny \
    Test::Most \
    JSON::Parse \
    Class::Struct \
    Bio::DB::Fasta \
    File::Copy \
    Bio::Seq \
    Bio::SeqIO \
    Bio::Tools::Run::Alignment::Muscle


RUN git clone https://github.com/dcouvin/CRISPRCasFinder.git

ENV ccf_build="/build/CRISPRCasFinder"
ENV distribution='Linux_x86_64'

#Install VMatch
RUN mkdir ${ccf_build}/src ${ccf_build}/bin \
    && cd ${ccf_build}/src \
    && wget http://vmatch.de/distributions/vmatch-2.3.0-${distribution}-64bit.tar.gz \
    && tar -zxf vmatch-2.3.0-${distribution}-64bit.tar.gz \
    && gcc -Wall -Werror -fPIC -O3 -shared vmatch-2.3.0-${distribution}-64bit/SELECT/sel392.c -o ${ccf_build}/sel392v2.so \
    && cp ${ccf_build}/src/vmatch-2.3.0-${distribution}-64bit/vmatch ${ccf_build}/bin/vmatch2 \
    && cp ${ccf_build}/src/vmatch-2.3.0-${distribution}-64bit/mkvtree ${ccf_build}/bin/mkvtree2 \
    && cp ${ccf_build}/src/vmatch-2.3.0-${distribution}-64bit/vsubseqselect ${ccf_build}/bin/vsubseqselect2 \
    && cd $ccf_build

#Install MacSyFinder
RUN cd $ccf_build \
    && wget https://dl.bintray.com/gem-pasteur/MacSyFinder/macsyfinder-1.0.5.tar.gz \
    && tar -zxf macsyfinder-1.0.5.tar.gz \
    && cd macsyfinder-1.0.5 \
    && python2.7 setup.py build \
    && python2.7 setup.py test -vv \
    && python2.7 setup.py install \
    && ln -s ../macsyfinder-1.0.5/bin/macsyfinder \
    && cd $ccf_build \
    && rm macsyfinder-1.0.5.tar.gz

COPY ./database/CAS-TypeVF.xml ${ccf_build}/CasFinder-2.0.3/DEF-SubTyping-2.0.3
COPY ./database/Cas14.hmm ${ccf_build}/CasFinder-2.0.3/CASprofiles-2.0.3

RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID ccf_user

RUN chown -R ccf_user:$GROUP_ID /build

USER ccf_user

ENV PATH "$PATH:${ccf_build}/bin"
ENV MACSY_HOME="${ccf_build}/macsyfinder-1.0.5"
